sonar.organization=bader2424
sonar.projectKey=bader2424_tic-tac-game
sonar.projectName=tic-tac-game
sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=dist/**,node_modules/**,helm/**,argocd/**
sonar.sourceEncoding=UTF-8
