replicaCount: 1

image:
  repository: bader1937/tic-tac-game
  tag: sha-ccaa7c5733a28bcfcae447f84ee33d14ff23b558
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

containerPort: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

serviceAccount:
  create: false

livenessProbe:
  path: /
  port: 80
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 5
